### ISSUE TITLE
Vimeo Only Intermittently Detected/Processed

### ISSUE THREAD

**Issue by CrowdForge** [WebDevStudios/Automatic-Featured-Images-from-Videos#39] opened 2016-11-30 17:19 UTC
Tried various Vimeo videos in bulk and single and many fail to process.

**Comment by binarygary** [comment] 2016-12-01 23:36
Suggest closing https://github.com/WebDevStudios/Automatic-Featured-Images-from-Videos/issues/38 as the issue is the same.

Current logic:
Check if the content contains a vimeo URL.  
If so we proceed to wds_get_vimeo_details() and retrieve details.  

However, the current logic assumes the video was 200 and not 301 or 404.  As a result a 301 or 404 video will not load the a video URL but will present with a vimeo id meaning we set meta as though a valid video exists.

**Comment by tw2113** [comment] 2018-02-24 02:32
Not pushed yet due to public wifi restrictions, but we will not save if we don't have data available. Instead of checking for the existence of the video ID, which we will have, we'll instead only save if we have data about the video.

**Closed by tw2113** 2018-02-24 02:32 UTC
Labels: bug
